# Generated by Django 6.0.2 on 2026-02-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0002_myappointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointments',
            old_name='datetime',
            new_name='date',
        ),
    ]
