# Generated by Django 6.0.2 on 2026-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareApp', '0003_rename_datetime_myappointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappointments',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
